{{- if and .Values.auditTrail.minio.enabled (not .Values.auditTrail.minio.existingSecret) }}
{{- $name := include "ontrack.minio.fullname" . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $name }}
  labels:
    {{- include "ontrack.labels.minio" . | nindent 4 }}
data:
  {{ .Values.auditTrail.minio.rootUserKey }}: {{ include "ontrack.secretPassword" (dict
    "secretName" $name
    "secretKey" .Values.auditTrail.minio.rootUserKey
    "context" .
    ) | b64enc | quote }}
  {{ .Values.auditTrail.minio.rootPasswordKey }}: {{ include "ontrack.secretPassword" (dict
    "secretName" $name
    "secretKey" .Values.auditTrail.minio.rootPasswordKey
    "context" .
    ) | b64enc | quote }}
{{- end }}
