{{- if and (eq .Values.ontrack.config.key_store "secret") .Values.ontrack.config.secret_key_store.external.enabled }}
{{- $external := .Values.ontrack.config.secret_key_store.external }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ontrack-encryption-key
spec:
  refreshInterval: {{ $external.refreshInterval | quote }}
  secretStoreRef:
    name: {{ $external.store.name | quote }}
    kind: {{ $external.store.kind }}
  target:
    name: {{ .Values.ontrack.config.secret_key_store.secret_name }}
  data:
    - secretKey: net.nemerosa.ontrack.security.EncryptionServiceImpl.encryption
      remoteRef:
        key: {{ $external.store.path | quote }}
        property: {{ $external.store.key | quote }}
        decodingStrategy: Base64
        conversionStrategy: Default
        metadataPolicy: None
    {{- with $external.auditTrail }}
    {{- if .key }}
    - secretKey: audit-trail.ed25519
      remoteRef:
        key: {{ .path | default $external.store.path | quote }}
        property: {{ .key | quote }}
        decodingStrategy: {{ .decodingStrategy | default "None" }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- end }}
{{- end }}
